Repository ucsb-cs156-s25/proj-rec-s25-14, pull requests merged in 2025-05, with the labels that each got.

#30 Fixed Bug - Student should be true when new user logs in
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
Labels: 5

#34 creating placeholder pages for index, create, and edit
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/RequestType/RequestTypeCreatePage.js
  frontend/src/main/pages/RequestType/RequestTypeEditPage.js
  frontend/src/main/pages/RequestType/RequestTypeIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/RequestType/RequestTypeCreatePage.test.js
  frontend/src/tests/pages/RequestType/RequestTypeEditPage.test.js
  frontend/src/tests/pages/RequestType/RequestTypeIndexPage.test.js
Labels: 5, Merge Candidate-CI

#35 FEATURE: GET all recommendation requests endpoint for Admin
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, Merge Candidate-CI

#38 implementing request type table
  frontend/src/fixtures/recommendationTypeFixtures.js
  frontend/src/main/components/RequestType/RequestTypeTable.js
  frontend/src/main/utils/RequestTypeUtils.js
  frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js
  frontend/src/stories/components/RequestType/RequestTypeTable.stories.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
  frontend/src/tests/components/RequestType/RequestTypeTable.test.js
  frontend/src/tests/utils/RequestTypeUtils.test.js
Labels: 10

#53 Updating HomePageWebIT to Test for Main Branch Update
  src/test/java/edu/ucsb/cs156/rec/web/HomePageWebIT.java
Labels: 5, Merge Candidate-CI

#31 Changed frontend to parse the ISO formatted dates using substring and updated tests for Recommendation Request Table
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/main/utils/dateutils.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
Labels: 10

#39 SUBISSUE: Date completed is stored to backend and reflected on table when Professor completes a Request
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 5, Merge Candidate-CI

#40 SUBISSUE: Professor Role can modify the status of a Request (Backend)
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/resources/db/migration/changelog-master.json
  src/main/resources/db/migration/changes/RecommendationRequest-001.json
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, FIXME-Merge Conflicts

#46 remove frontend toggling student
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: 10

#49 removing toggle for student from backend
  src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/UsersControllerTests.java
Labels: 5

#50 Create new page: All requests for admin
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/main/pages/AdminRequestsPage.js
  frontend/src/tests/pages/AdminRequestsPage.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/web/HomePageWebIT.java
Labels: 10, Merge Candidate-CI

#45 Modified RecommendationRequest recommendationType to be a foreign key to RequestType
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/resources/db/migration/changelog-master.json
  src/main/resources/db/migration/changes/RecommendationRequest-002.json
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestTests.java
Labels: Ready-For-Staff
